## matmul backward test case

In [31]:
import torch
import torch.nn as nn

In [48]:

x = torch.tensor([[[ 1.9170,  0.7433, -1.6831, -0.5770],
         [ 0.5002, -0.1631, -0.6377,  0.1790],
         [ 0.8014,  0.9574,  0.5211,  0.6669]],

        [[ 0.0507, -0.7415,  0.7975, -0.1952],
         [-0.0915, -0.2075, -0.6837, -1.4144],
         [-1.0925, -0.9400,  2.0981,  2.5490]]])
weight =  torch.tensor([[ 0.5496, -1.0675, -0.3498, -1.7053, -0.0094],
        [ 0.8118,  0.6951,  1.7514, -0.0827, -0.7742],
        [ 0.6460, -0.5852,  1.0690,  2.4317, -1.1704],
        [ 0.0139, -0.5536, -0.0932,  0.6729, -0.1479]])
bias = torch.tensor([-0.5602, -0.6464, -0.2690,  0.5687, -0.1302])

print(x)
print(weight.transpose(-1,-2))
print(bias)

tensor([[[ 1.9170,  0.7433, -1.6831, -0.5770],
         [ 0.5002, -0.1631, -0.6377,  0.1790],
         [ 0.8014,  0.9574,  0.5211,  0.6669]],

        [[ 0.0507, -0.7415,  0.7975, -0.1952],
         [-0.0915, -0.2075, -0.6837, -1.4144],
         [-1.0925, -0.9400,  2.0981,  2.5490]]])
tensor([[ 0.5496,  0.8118,  0.6460,  0.0139],
        [-1.0675,  0.6951, -0.5852, -0.5536],
        [-0.3498,  1.7514,  1.0690, -0.0932],
        [-1.7053, -0.0827,  2.4317,  0.6729],
        [-0.0094, -0.7742, -1.1704, -0.1479]])
tensor([-0.5602, -0.6464, -0.2690,  0.5687, -0.1302])


In [49]:
x.requires_grad_(True)
matmul = nn.Linear(4,8)
matmul.weight = nn.Parameter(weight.transpose(-1,-2))
matmul.bias = nn.Parameter(bias)
y = matmul(x)
y.retain_grad()
print(y)

tensor([[[ 1.4913e-03, -8.7175e-01, -1.3832e+00, -7.2429e+00,  1.3316e+00],
         [-8.2716e-01, -1.0196e+00, -1.4280e+00, -1.7010e+00,  7.1126e-01],
         [ 1.0034e+00, -1.5105e+00,  1.6224e+00,  8.3881e-01, -1.5875e+00]],

        [[-6.2181e-01, -1.5746e+00, -7.1468e-01,  2.3515e+00, -4.6113e-01],
         [-1.2403e+00,  4.9016e-01, -1.1995e+00, -1.8724e+00,  1.0407e+00],
         [-5.3293e-01, -2.7725e+00,  4.7214e-01,  9.3266e+00, -2.2248e+00]]],
       grad_fn=<ViewBackward0>)


In [50]:
loss = y.sum()

In [51]:
loss.backward()
print(y.grad)
print(x.grad)
print(matmul.weight.grad.transpose(-1,-2))
print(matmul.bias.grad)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[-2.5824,  2.4014,  2.3911, -0.1079],
         [-2.5824,  2.4014,  2.3911, -0.1079],
         [-2.5824,  2.4014,  2.3911, -0.1079]],

        [[-2.5824,  2.4014,  2.3911, -0.1079],
         [-2.5824,  2.4014,  2.3911, -0.1079],
         [-2.5824,  2.4014,  2.3911, -0.1079]]])
tensor([[ 2.0853,  2.0853,  2.0853,  2.0853,  2.0853],
        [-0.3514, -0.3514, -0.3514, -0.3514, -0.3514],
        [ 0.4122,  0.4122,  0.4122,  0.4122,  0.4122],
        [ 1.2083,  1.2083,  1.2083,  1.2083,  1.2083]])
tensor([6., 6., 6., 6., 6.])
